# Generated by Django 3.2.8 on 2021-12-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textutils', '0002_auto_20211213_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=100)),
                ('feedback', models.TextField(max_length=250)),
            ],
            options={
                'db_table': 'userfeedback',
            },
        ),
        migrations.RemoveField(
            model_name='contact',
            name='content',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='timeStamp',
        ),
        migrations.AddField(
            model_name='contact',
            name='Issue',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterModelTable(
            name='contact',
            table='wordcountercontact',
        ),
    ]
