# Generated by Django 3.2.8 on 2021-12-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textutils', '0004_alter_userfeedback_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
