# Generated by Django 3.2.8 on 2021-12-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textutils', '0005_auto_20211216_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='feedback_date',
            field=models.DateField(max_length=250, null=True),
        ),
    ]
