# Generated by Django 3.2.8 on 2021-12-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textutils', '0007_alter_userfeedback_feedback_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='feedback_date',
            field=models.DateField(default='', max_length=250),
        ),
    ]
