# Generated by Django 3.2.8 on 2021-12-24 09:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('textutils', '0010_alter_userfeedback_feedback_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='feedback_date',
            field=models.DateField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
