# Generated by Django 4.0 on 2022-01-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textutils', '0015_alter_userfeedback_feedback_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSaver',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=250, upload_to='')),
                ('filesave_date', models.DateField(auto_now_add=True, max_length=30)),
            ],
        ),
    ]
