# Generated by Django 4.0 on 2022-01-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textutils', '0017_alter_filesaver_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesaver',
            name='sno',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
