# Generated by Django 4.0 on 2022-01-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textutils', '0018_alter_filesaver_sno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesaver',
            name='sno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
