# Generated by Django 4.0 on 2022-01-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textutils', '0019_alter_filesaver_sno'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextHistory',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('textcontent', models.FileField(max_length=250, upload_to='')),
                ('contentsave_date', models.DateTimeField(auto_now_add=True, max_length=30)),
            ],
            options={
                'db_table': 'texthistory',
            },
        ),
        migrations.DeleteModel(
            name='FileSaver',
        ),
    ]
