# Generated by Django 4.0 on 2022-01-10 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textutils', '0020_texthistory_delete_filesaver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='texthistory',
            old_name='textcontent',
            new_name='text',
        ),
    ]
