# Generated by Django 4.0 on 2022-01-11 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textutils', '0023_texthistory_id_alter_texthistory_sno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='texthistory',
            old_name='sno',
            new_name='user',
        ),
    ]
