# Generated by Django 4.0 on 2022-01-11 02:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('textutils', '0025_alter_texthistory_id_alter_texthistory_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texthistory',
            name='user',
            field=models.ForeignKey(default=datetime.datetime(2022, 1, 11, 2, 40, 57, 975020, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
