# Generated by Django 4.0 on 2022-01-11 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textutils', '0026_alter_texthistory_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TextHistory',
        ),
    ]
