# Generated by Django 4.0 on 2022-01-11 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('textutils', '0027_delete_texthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextContentHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=2500)),
                ('contentsavedate', models.DateTimeField(auto_now_add=True, max_length=30)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'db_table': 'textcontenthistory',
            },
        ),
    ]
