# Generated by Django 4.0 on 2022-01-11 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('textutils', '0030_alter_textcontenthistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textcontenthistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
