# Generated by Django 4.0 on 2022-01-11 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textutils', '0031_alter_textcontenthistory_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textcontenthistory',
            old_name='user',
            new_name='user_id',
        ),
    ]
