# Generated by Django 4.0 on 2022-01-11 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textutils', '0032_rename_user_textcontenthistory_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textcontenthistory',
            old_name='user_id',
            new_name='user',
        ),
    ]
